### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by zeqi2000** [AlumiK/paper-scraper#1]
when use pip install dblp

report an error

Collecting dblp
  Using cached dblp-0.1.0.tar.gz (3.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-f4zi1g3d/dblp_bb60d643fe3c44fb91aa69fc47bef1fa/setup.py", line 12, in <module>
          long_description=open('README.md').read(),
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by jiangyinzuo** [comment]
Seems that `pip install dblp` does not install this library. (See: https://pypi.org/project/dblp/)

This library may not have published to pip.

**Comment by alumik** [comment]
Thank you for bringing this issue to my attention. The dblp repository is intended as a tool script and was not designed for distribution via PyPI. The error occurs because the package metadata is not set up for a proper PyPI release. To resolve this, you can clone the repository directly and use it manually.
